module.exports = {
    LOGIN_ACTION: "LOGIN_ACTION",
    LOGOUT_ACTION: "LOGOUT_ACTION",
    GET_TOKEN_ACTION: "GET_TOKEN_ACTION",
    
    LOGIN_SUCCESSFULL: "LOGIN_SUCCESSFULL",
    LOGIN_ERROR: "LOGIN_ERROR",
    TOKEN_SUCCESSFULL: "TOKEN_SUCCESSFULL",
    TOKEN_ERROR: "TOKEN_ERROR"
}